# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  pod 'Moya'
  pod 'RealmSwift'
  pod 'ObjectMapper'
  pod 'Kingfisher', '~> 4.0'
  pod 'SwiftInstagram', '~> 1.1.2'
  # Pods for CountMe

end
