# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Instat' do
  pod 'SwiftInstagram', '~> 1.1.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end